### ISSUE TITLE
When $getUpdates->timeout > 30, curl errors

### ISSUE THREAD

**Issue by Skons** [botstan/API#13]
When a timeout of 30 or more is provided for getUpdates, and there is no update for the bot curl will throw an error.

```
[19-May-2018 20:27:43 UTC] PHP Fatal error:  Uncaught Exception: Curl request failed: Operation timed out after 30001 milliseconds with 0 bytes received in .../vendor/botstan/api/src/base/Curl.php:208
Stack trace:
#0 .../vendor/botstan/api/src/base/Curl.php(185): api\base\Curl->error(false)
#1 .../vendor/botstan/api/src/base/Curl.php(138): api\base\Curl->send('POST', 'https://api.tel...', true)
#2 .../vendor/botstan/api/src/base/Request.php(196): api\base\Curl->post('https://api.tel...', true)
#3 .../vendor/botstan/api/src/method/Method.php(64): api\base\Request->send()
...
  thrown in .../vendor/botstan/api/src/base/Curl.php on line 208
```

Code to reproduce
```
$getUpdates = $api->getUpdates();
$getUpdates->timeout = 31;
$getUpdates->send();
```

**Comment by mehdikhody** [comment]
It should be worked.
```php
set_time_limit(0);
$getUpdates = $api->getUpdates();
$getUpdates->timeout = 31;
$getUpdates->send();
```
